### PR TITLE
Add an optimisation, more tests and support for enums.

### PR DESCRIPTION
**Pull request by fduminy**
The test BehaimTest.testBuild_2Params_twoInstances() is ignored since it doesn't pass : I have created the issue #3 for that.

### CODE REVIEW

**Comment by fduminy** [comment]
I have added support for enum. So, it should fix issue #1.

**Comment by fduminy** [comment]
Hello @chrisgleissner, can you accept the PR please ?

**Review by chrisgleissner — APPROVED** [review]
Thanks for the pull request - it looks good.

**Comment by chrisgleissner** [comment]
Thanks for your changes, @fduminy - this is now all merged into master. Great work. Sorry it took a while to get merged in.

**Comment by chrisgleissner** [comment]
Behaim 0.1.0 has been released to the Maven Central repository: https://oss.sonatype.org/#nexus-search;quick~behaim

**Comment by fduminy** [comment]
@chrisgleissner I think #1 can be closed since I added support for enum.

**Pull request merged**
